# docker build -t react-app:dg -f deploy/Dockerfile_for_exec_bash .
# docker run -p 3000:3000 react-app:dg
# Use `-d` flag to have container id returned, once it is started
#   docker run -d -p 3000:3000 react-app:dg
# or get container id with `docker ps`
# exec into container:
#   docker exec -it <CONTAINER_ID> bash

# Use official Node.js LTS image as the base
FROM node:20-alpine

# Set working directory inside the container
WORKDIR /app

# Install git and bash
RUN apk update && apk add --no-cache git bash

# Clone the React application repository
# RUN git clone https://github.com/gitname/react-gh-pages.git .
RUN git clone https://github.com/takotime808/danigirl.git .

# COPY . .

# Install dependencies
RUN npm install

# # Run tests
# RUN npm test -- --watchAll=false

# Build the React application
RUN npm run build

# Expose port for application preview (optional)
EXPOSE 3000

# Start the app
CMD ["npm", "start"]
